In [1]:
import json
import pandas as pd
import numpy as np
import re

# create a file path so code is more dynamic if location of data changes

In [2]:
file_dir = "C:\\Users\\Frank Bucalo\\Desktop\\classwork\\Movies-ETL\\"

In [3]:
f'{file_dir}wikipedia-movies.json'

'C:\\Users\\Frank Bucalo\\Desktop\\classwork\\Movies-ETL\\wikipedia-movies.json'

# load JSON into a list of dictionaries
> load( )  

use "with open" to both & close the file while in use

In [4]:
with open(f'{file_dir}wikipedia-movies.json', mode='r') as file:
    wiki_movies_raw = json.load(file)

In [5]:
len(wiki_movies_raw)

7311

# use index slices to review the dictionaries

In [6]:
# First 5 records
wiki_movies_raw[:5]

[{'url': 'https://en.wikipedia.org/wiki/The_Adventures_of_Ford_Fairlane',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098987/',
  'title': 'The Adventures of Ford Fairlane',
  'Directed by': 'Renny Harlin',
  'Produced by': ['Steve Perry', 'Joel Silver'],
  'Screenplay by': ['David Arnott', 'James Cappe', 'Daniel Waters'],
  'Story by': ['David Arnott', 'James Cappe'],
  'Based on': ['Characters', 'by Rex Weiner'],
  'Starring': ['Andrew Dice Clay',
   'Wayne Newton',
   'Priscilla Presley',
   'Lauren Holly',
   'Morris Day',
   'Robert Englund',
   "Ed O'Neill"],
  'Narrated by': 'Andrew "Dice" Clay',
  'Music by': ['Cliff Eidelman', 'Yello'],
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Michael Tronick',
  'Productioncompany ': 'Silver Pictures',
  'Distributed by': '20th Century Fox',
  'Release date': ['July 11, 1990', '(', '1990-07-11', ')'],
  'Running time': '102 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$21.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/After_Dark,_My_Sweet',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098994/',
  'title': 'After Dark, My Sweet',
  'Directed by': 'James Foley',
  'Produced by': ['Ric Kidney', 'Robert Redlin'],
  'Screenplay by': ['James Foley', 'Robert Redlin'],
  'Based on': ['the novel', 'After Dark, My Sweet', 'by', 'Jim Thompson'],
  'Starring': ['Jason Patric',
   'Rachel Ward',
   'Bruce Dern',
   'George Dickerson'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Mark Plummer',
  'Edited by': 'Howard E. Smith',
  'Productioncompany ': 'Avenue Pictures',
  'Distributed by': 'Avenue Pictures',
  'Release date': ['May 17, 1990',
   '(',
   '1990-05-17',
   ')',
   '(Cannes Film Market)',
   'August 24, 1990',
   '(',
   '1990-08-24',
   ')',
   '(United States)'],
  'Running time': '114 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$6 million',
  'Box office': '$2.7 million'},
 {'url': 'https://en.wikipedia.org/wiki/Air_America_(film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099005/',
  'title': 'Air America',
  'Directed by': 'Roger Spottiswoode',
  'Produced by': 'Daniel Melnick',
  'Screenplay by': ['John Eskow', 'Richard Rush'],
  'Based on': ['Air America', 'by', 'Christopher Robbins'],
  'Starring': ['Mel Gibson',
   'Robert Downey Jr.',
   'Nancy Travis',
   'David Marshall Grant',
   'Lane Smith'],
  'Music by': 'Charles Gross',
  'Cinematography': 'Roger Deakins',
  'Edited by': ['John Bloom', 'Lois Freeman-Fox'],
  'Productioncompany ': ['Carolco Pictures', 'IndieProd Company'],
  'Distributed by': 'TriStar Pictures',
  'Release date': ['August 10, 1990', '(', '1990-08-10', ')'],
  'Running time': '113 minutes',
  'Country': 'United States',
  'Language': ['English', 'Lao'],
  'Budget': '$35 million',
  'Box office': '$57,718,089'},
 {'url': 'https://en.wikipedia.org/wiki/Alice_(1990_film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099012/',
  'title': 'Alice',
  'Directed by': 'Woody Allen',
  'Produced by': 'Robert Greenhut',
  'Written by': 'Woody Allen',
  'Starring': ['Alec Baldwin',
   'Blythe Danner',
   'Judy Davis',
   'Mia Farrow',
   'William Hurt',
   'Keye Luke',
   'Joe Mantegna',
   'Bernadette Peters'],
  'Cinematography': 'Carlo Di Palma',
  'Edited by': 'Susan E. Morse',
  'Distributed by': 'Orion Pictures',
  'Release date': ['December 25, 1990', '(', '1990-12-25', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$12 million',
  'Box office': '$7,331,647'},
 {'url': 'https://en.wikipedia.org/wiki/Almost_an_Angel',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099018/',
  'title': 'Almost an Angel',
  'Directed by': 'John Cornell',
  'Produced by': 'John Cornell',
  'Written by': 'Paul Hogan',
  'Starring': ['Paul Hogan', 'Elias Koteas', 'Linda Kozlowski'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Russell Boyd',
  'Edited by': 'David Stiven',
  'Distributed by': 'Paramount Pictures',
  'Release date': 'December 19, 1990',
  'Running time': '95 minutes',
  'Country': 'US',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$6,939,946 (USA)'}]

In [7]:
# Last 5 records
wiki_movies_raw[-5:]

[{'url': 'https://en.wikipedia.org/wiki/Holmes_%26_Watson',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt1255919/',
  'title': 'Holmes & Watson',
  'Directed by': 'Etan Cohen',
  'Produced by': ['Will Ferrell',
   'Adam McKay',
   'Jimmy Miller',
   'Clayton Townsend'],
  'Screenplay by': 'Etan Cohen',
  'Based on': ['Sherlock Holmes',
   'and',
   'Dr. Watson',
   'by',
   'Sir Arthur Conan Doyle'],
  'Starring': ['Will Ferrell',
   'John C. Reilly',
   'Rebecca Hall',
   'Rob Brydon',
   'Steve Coogan',
   'Ralph Fiennes'],
  'Music by': 'Mark Mothersbaugh',
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Dean Zimmerman',
  'Productioncompanies ': ['Columbia Pictures',
   'Gary Sanchez Productions',
   'Mosaic Media Group',
   'Mimran Schur Pictures'],
  'Distributed by': 'Sony Pictures Releasing',
  'Release date': ['December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '90 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$42 million',
  'Box office': '$41.9 million'},
 {'url': 'https://en.wikipedia.org/wiki/Vice_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt6266538/',
  'title': 'Vice',
  'Directed by': 'Adam McKay',
  'Produced by': ['Brad Pitt',
   'Dede Gardner',
   'Jeremy Kleiner',
   'Kevin J. Messick',
   'Will Ferrell',
   'Adam McKay'],
  'Written by': 'Adam McKay',
  'Starring': ['Christian Bale',
   'Amy Adams',
   'Steve Carell',
   'Sam Rockwell',
   'Tyler Perry',
   'Alison Pill',
   'Lily Rabe',
   'Jesse Plemons'],
  'Music by': 'Nicholas Britell',
  'Cinematography': 'Greig Fraser',
  'Edited by': 'Hank Corwin',
  'Productioncompany ': ['Plan B Entertainment',
   'Gary Sanchez Productions',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['December 11, 2018',
   '(',
   '2018-12-11',
   ')',
   '(',
   'Samuel Goldwyn Theater',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '132 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$60 million',
  'Box office': '$76.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/On_the_Basis_of_Sex',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt4669788/',
  'title': 'On the Basis of Sex',
  'Directed by': 'Mimi Leder',
  'Produced by': 'Robert W. Cort',
  'Written by': 'Daniel Stiepleman',
  'Starring': ['Felicity Jones',
   'Armie Hammer',
   'Justin Theroux',
   'Sam Waterston',
   'Kathy Bates'],
  'Music by': 'Mychael Danna',
  'Cinematography': 'Michael Grady',
  'Edited by': 'Michelle Tesoro',
  'Productioncompanies ': ['Focus Features',
   '[1]',
   'Participant Media',
   '[1]',
   'Robert Cort Productions',
   '[1]',
   'Alibaba Pictures',
   '[2]'],
  'Distributed by': 'Focus Features',
  'Release date': ['November 8, 2018',
   '(',
   '2018-11-08',
   ')',
   '(',
   'AFI Fest',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '120 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$38.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/Destroyer_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt7137380/',
  'title': 'Destroyer',
  'Directed by': 'Karyn Kusama',
  'Produced by': ['Fred Berger', 'Phil Hay', 'Matt Manfredi'],
  'Written by': ['Phil Hay', 'Matt Manfredi'],
  'Starring': ['Nicole Kidman',
   'Sebastian Stan',
   'Toby Kebbell',
   'Tatiana Maslany',
   'Bradley Whitford',
   'Jade Pettyjohn',
   'Scoot McNairy'],
  'Music by': 'Theodore Shapiro',
  'Cinematography': 'Julie Kirkwood',
  'Edited by': 'Plummy Tucker',
  'Productioncompany ': ['30West',
   'Automatik Entertainment',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['August 31, 2018',
   '(',
   '2018-08-31',
   ')',
   '(',
   'Telluride',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '123 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$9 million',
  'Box office': '$5.5 million'},
 {'url': 'https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt9495224/',
  'title': 'Bandersnatch',
  'Directed by': 'David Slade',
  'Produced by': 'Russell McLean',
  'Written by': 'Charlie Brooker',
  'Starring': ['Fionn Whitehead',
   'Will Poulter',
   'Craig Parkinson',
   'Alice Lowe',
   'Asim Chaudhry'],
  'Music by': 'Brian Reitzell',
  'Cinematography': ['Aaron Morton', 'Jake Polonsky'],
  'Edited by': 'Tony Kearns',
  'Productioncompany ': ['House of Tomorrow', 'Netflix'],
  'Distributed by': 'Netflix',
  'Release date': ['28 December 2018', '(', '2018-12-28', ')'],
  'Running time': 'Variable; 90 minutes for default path',
  'Country': 'United Kingdom',
  'Language': 'English'}]

In [8]:
# Some records in the middle
wiki_movies_raw[3600:3605]

[{'url': 'https://en.wikipedia.org/wiki/Benji:_Off_the_Leash!',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315273/',
  'title': 'Benji: Off the Leash!',
  'Directed by': 'Joe Camp',
  'Written by': 'Joe Camp',
  'Starring': ['Benji', 'Nick Whitaker', 'Shaggy', 'Gypsy the Cockatoo'],
  'Music by': 'Antonio di Lorenzo',
  'Productioncompany ': 'Mulberry Square Productions',
  'Distributed by': 'Mulberry Square Productions',
  'Release date': ['March 26, 2004', '(', '2004-03-26', ')'],
  'Running time': '97 min',
  'Country': 'United States',
  'Language': 'English',
  'Box office': '$3,817,362'},
 {'url': 'https://en.wikipedia.org/wiki/The_Best_Thief_in_the_World',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0389796/',
  'title': 'The Best Thief in the World',
  'Directed by': 'Jacob Kornbluth',
  'Produced by': ['Tim Perrell', 'Nicola Usborne'],
  'Written by': 'Jacob Kornbluth',
  'Starring': ['Marc Rozendaal',
   'Michael Silverman',
   'David Warshofsky',
   'Audra McDonald',
   'Lois Smith'],
  'Music by': ['Prince Paul', 'and', 'Don Newkirk'],
  'Cinematography': 'Ben Kutchins',
  'Edited by': 'Stephanie Sterner',
  'Distributed by': 'Showtime Networks',
  'Release date': ['January 16, 2004', '(', '2004-01-16', ')'],
  'Running time': '93 minutes',
  'Country': 'United States',
  'Language': 'English'},
 {'url': 'https://en.wikipedia.org/wiki/Beyond_the_Sea_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0363473/',
  'title': 'Beyond the Sea',
  'Directed by': 'Kevin Spacey',
  'Produced by': ['Kevin Spacey',
   'Phillip Barry',
   'Dana Brunetti',
   'Arthur Friedman',
   'Jan Fantl',
   'Andy Paterson'],
  'Written by': ['Lewis Colick', 'Kevin Spacey'],
  'Starring': ['Kevin Spacey', 'Kate Bosworth', 'Bob Hoskins', 'John Goodman'],
  'Music by': 'Bobby Darin',
  'Cinematography': 'Eduardo Serra',
  'Edited by': 'Trevor Waite',
  'Productioncompany ': 'Trigger Street Productions',
  'Distributed by': ['Lionsgate Films',
   '(USA)',
   'Entertainment Film Distributors',
   '(UK)',
   'GAGA',
   '(Japan)',
   'Maple Pictures',
   '(Canada)'],
  'Release date': ['December 17, 2004', '(', '2004-12-17', ')'],
  'Running time': '118 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$8.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/The_Big_Bounce_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315824/',
  'title': 'The Big Bounce',
  'Directed by': 'George Armitage',
  'Produced by': ['George Armitage', 'Steve Bing'],
  'Screenplay by': 'Sebastian Gutierrez',
  'Based on': ['The Big Bounce', 'by', 'Elmore Leonard'],
  'Starring': ['Owen Wilson',
   'Charlie Sheen',
   'Morgan Freeman',
   'Sara Foster',
   'Gary Sinise'],
  'Music by': 'George S. Clinton',
  'Cinematography': 'Jeffrey L. Kimball',
  'Edited by': 'Barry Malkin',
  'Productioncompany ': 'Shangri-La Entertainment',
  'Distributed by': 'Warner Bros. Pictures',
  'Release date': ['January 30, 2004', '(', '2004-01-30', ')'],
  'Running time': '88 minutes',
  'Language': 'English',
  'Budget': '$50 million',
  'Box office': '$6.8 million'},
 {'url': 'https://en.wikipedia.org/wiki/Birth_(film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0337876/',
  'title': 'Birth',
  'Directed by': 'Jonathan Glazer',
  'Produced by': ['Lizie Gower', 'Nick Morris', 'Jean-Louis Piel'],
  'Written by': ['Jean-Claude Carrière', 'Milo Addica', 'Jonathan Glazer'],
  'Starring': ['Nicole Kidman',
   'Cameron Bright',
   'Danny Huston',
   'Lauren Bacall'],
  'Music by': 'Alexandre Desplat',
  'Cinematography': 'Harris Savides',
  'Edited by': ['Sam Sneade', 'Claus Wehlisch'],
  'Distributed by': 'New Line Cinema',
  'Release date': ['November 8, 2004', '(', '2004-11-08', ')'],
  'Running time': '96 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$23.9 million'}]

In [9]:
movies_meta = pd.read_csv(f'{file_dir}movies_metadata.csv', low_memory=False)
ratings = pd.read_csv(f'{file_dir}ratings.csv')

In [10]:
movies_meta.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

# sample to ensure data import looks correct
> sample( )

In [11]:
movies_meta.sample(n=5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
10997,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,38344,tt0410400,en,On a Clear Day,After decades of laboring as a Glasgow shipbui...,...,2005-08-18,0.0,98.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Anything is possible,On a Clear Day,False,6.4,9.0
20483,False,NaN,0,[],NaN,359353,tt0198999,en,The Scarecrow,"Just before the Salem Witch Trials, an embitte...",...,1972-01-10,0.0,105.0,[],Released,NaN,The Scarecrow,False,0.0,0.0
5442,False,NaN,9000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9685,tt0280760,en,Igby Goes Down,A young man's peculiar upbringing renders him ...,...,2002-09-13,4777465.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Insanity is relative.,Igby Goes Down,False,6.5,95.0
24679,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,91580,tt0094908,en,Cool Blue,"Dustin, an aspiring painter meets this woman n...",...,1990-02-27,0.0,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Dustin thought his life was a mess... now he's...,Cool Blue,False,4.5,5.0
22045,False,NaN,3200000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,43213,tt1085382,en,Chicago Overcoat,The fates of an aging hitman and a washed up d...,...,2009-10-10,0.0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The glory days are back,Chicago Overcoat,False,6.1,5.0

In [12]:
movies_meta.tail()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [13]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [14]:
ratings.sample(n=5)

          userId  movieId  rating   timestamp
17957028  186460      357     4.0   835777626
3952640    41131     8827     3.5  1228435970
4717532    48498      708     3.0   938596851
16280322  169170     6711     5.0  1206520075
23456269  243453     3809     4.0  1093045266

In [15]:
ratings.tail()

          userId  movieId  rating   timestamp
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

# convert to DataFrame for further inspection

In [16]:
wiki_movies_df = pd.DataFrame(wiki_movies_raw)

wiki_movies_df.head(10)

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990.0,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990.0,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990.0,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990.0,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990.0,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://en.wikipedia.org/wiki/The_Ambulance,1990.0,https://www.imdb.com/title/tt0099026/,The Ambulance,Larry Cohen,"[Larry Cohen, Moctesuma Esparza, Robert Katz]",NaN,NaN,NaN,"[Eric Roberts, James Earl Jones, Red Buttons, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://en.wikipedia.org/wiki/American_Dream_(...,1990.0,https://www.imdb.com/title/tt0099028/,American Dream,"[Barbara Kopple, Co-directors:, Cathy Caplan, ...","[Arthur Cohn, Barbara Kopple]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://en.wikipedia.org/wiki/American_Ninja_4...,1990.0,https://www.imdb.com/title/tt0101326/,American Ninja 4: The Annihilation,Cedric Sundstrom,Ovidio G Assonitis,NaN,NaN,NaN,"[Michael Dudikoff, David Bradley, James Booth,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://en.wikipedia.org/wiki/Andre%27s_Mother,1990.0,https://www.imdb.com/title/tt0099037/,Andre's Mother,Deborah Reinisch,"[Sarah Green, Deborah Reinisch]",NaN,NaN,NaN,"[Richard Thomas, Sada Thompson, Sylvia Sidney]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://en.wikipedia.org/wiki/Angel_Town_(film),1990.0,https://www.imdb.com/title/tt0099039/,Angel Town,Eric Karson,"[Ash R. Shah, Eric Karson]",NaN,NaN,NaN,"[Olivier Gruner, Theresa Saldana, Frank Aragon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# convert columns to a list to more easily view
> .tolist( )

In [17]:
wiki_movies_df.columns.tolist()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resting place',
 'Occupation',
 'Years active',
 'Spouse(s)',
 'Children',
 'Parent(s)',
 'Genres',
 'Instruments',
 'Labels',
 'Website',
 'Traditional',
 'Mandarin',
 'Type',
 'Industry',
 'Fate',
 'Founded',
 'Founder',
 'Headquarters',
 'Parent',
 'Released',
 'Recorded',
 'Venue',
 'Length',
 'Label',
 'Director',
 'Producer',
 'Area',
 'Coordinates',
 'Status',
 'Opening date',
 'Closing date',
 'Replaced',
 'Replaced by',
 'Name',
 'Attraction type',
 'Music',
 'Duration',
 'Simplified Chinese',
 'Traditional Chinese',
 'Hanyu Pinyin',
 'Literal meaning',
 'Transcriptions',
 'Bopomofo',
 'Gwoyeu Romatzyh',
 'Wade–Giles',
 'IPA',
 'Yale Romanization',
 'Jyutping',
 'Hokkien POJ',
 'Animation by',
 'Color process',
 'Engine(s)',
 'Genre(s)',
 'Actor control',
 'Production company',
 'Release(s)',
 'Format(s)',
 'Simplified',
 'Characters',
 'Date premiered',
 'Place premiered',
 'Setting',
 'Original language',
 'Subject',
 'Published',
 'Dewey Decimal',
 'Text',
 'Illustrator',
 'Original title',
 'Published in English',
 'French',
 'Developed by',
 'Ending theme',
 'No. of seasons',
 'Nationality',
 'Portrayed by',
 'Alias',
 'Species',
 'Gender',
 'Family',
 'Alma mater',
 'Camera setup',
 'Novel(s)',
 'Comics',
 'Film(s)',
 'Screen story by',
 'Hangul',
 'Revised Romanization',
 'McCune–Reischauer',
 'Developer(s)',
 'Publisher(s)',
 'Designer(s)',
 'Programmer(s)',
 'Artist(s)',
 'Writer(s)',
 'Engine',
 'Platform(s)',
 'Release',
 'Mode(s)',
 'Original work',
 'Television series',
 'Japanese',
 'Hepburn',
 'Literally',
 'Cantonese',
 'Full name',
 'Height',
 'Seasons',
 'Chinese',
 'Other names',
 'Relatives',
 'Yiddish',
 'Formerly',
 'Key people',
 'Total assets',
 'Owner',
 'Number of employees',
 'Divisions',
 'Subsidiaries',
 'Arabic',
 'Romanized',
 'Predecessor',
 'Founders',
 'Area served',
 'Products',
 'Services',
 'Russian',
 'Hebrew',
 'Revenue',
 'Operating income',
 'Polish']

# use list comprehensions to filter

In [18]:
wiki_movies = [movie for movie in wiki_movies_raw
    if ('Director' in movie or 'Directed by' in movie)
    and 'imdb_link' in movie]

len(wiki_movies)

7080

In [19]:
filtered_movies_df = pd.DataFrame(wiki_movies)

filtered_movies_df.head(10)

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://en.wikipedia.org/wiki/The_Ambulance,1990,https://www.imdb.com/title/tt0099026/,The Ambulance,Larry Cohen,"[Larry Cohen, Moctesuma Esparza, Robert Katz]",NaN,NaN,NaN,"[Eric Roberts, James Earl Jones, Red Buttons, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://en.wikipedia.org/wiki/American_Dream_(...,1990,https://www.imdb.com/title/tt0099028/,American Dream,"[Barbara Kopple, Co-directors:, Cathy Caplan, ...","[Arthur Cohn, Barbara Kopple]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://en.wikipedia.org/wiki/American_Ninja_4...,1990,https://www.imdb.com/title/tt0101326/,American Ninja 4: The Annihilation,Cedric Sundstrom,Ovidio G Assonitis,NaN,NaN,NaN,"[Michael Dudikoff, David Bradley, James Booth,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://en.wikipedia.org/wiki/Andre%27s_Mother,1990,https://www.imdb.com/title/tt0099037/,Andre's Mother,Deborah Reinisch,"[Sarah Green, Deborah Reinisch]",NaN,NaN,NaN,"[Richard Thomas, Sada Thompson, Sylvia Sidney]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://en.wikipedia.org/wiki/Angel_Town_(film),1990,https://www.imdb.com/title/tt0099039/,Angel Town,Eric Karson,"[Ash R. Shah, Eric Karson]",NaN,NaN,NaN,"[Olivier Gruner, Theresa Saldana, Frank Aragon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie
                   and 'No. of episodes' not in movie]

In [21]:
only_movies_df = pd.DataFrame(wiki_movies)

only_movies_df.head(10)

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://en.wikipedia.org/wiki/The_Ambulance,1990,https://www.imdb.com/title/tt0099026/,The Ambulance,Larry Cohen,"[Larry Cohen, Moctesuma Esparza, Robert Katz]",NaN,NaN,NaN,"[Eric Roberts, James Earl Jones, Red Buttons, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://en.wikipedia.org/wiki/American_Dream_(...,1990,https://www.imdb.com/title/tt0099028/,American Dream,"[Barbara Kopple, Co-directors:, Cathy Caplan, ...","[Arthur Cohn, Barbara Kopple]",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://en.wikipedia.org/wiki/American_Ninja_4...,1990,https://www.imdb.com/title/tt0101326/,American Ninja 4: The Annihilation,Cedric Sundstrom,Ovidio G Assonitis,NaN,NaN,NaN,"[Michael Dudikoff, David Bradley, James Booth,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://en.wikipedia.org/wiki/Andre%27s_Mother,1990,https://www.imdb.com/title/tt0099037/,Andre's Mother,Deborah Reinisch,"[Sarah Green, Deborah Reinisch]",NaN,NaN,NaN,"[Richard Thomas, Sada Thompson, Sylvia Sidney]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://en.wikipedia.org/wiki/Angel_Town_(film),1990,https://www.imdb.com/title/tt0099039/,Angel Town,Eric Karson,"[Ash R. Shah, Eric Karson]",NaN,NaN,NaN,"[Olivier Gruner, Theresa Saldana, Frank Aragon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# create a function to perform cleaning
### create a non-destructive copy

In [22]:
def clean_movie(movie):
    movie = dict(movie)
    return movie

In [23]:
only_movies_df[only_movies_df['Arabic'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
6834,https://en.wikipedia.org/wiki/The_Insult_(film),2018,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,Case No. 23,NaN,NaN,NaN,قضية رقم ٢٣,Qadiyya raqm 23,NaN,NaN,NaN
7058,https://en.wikipedia.org/wiki/Capernaum_(film),2018,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,کفرناحوم‎,NaN,NaN,NaN,NaN

In [24]:
only_movies_df['year'].value_counts()

2006    403
2013    363
1997    342
1996    338
1995    295
2012    294
2007    290
1994    277
1990    261
2018    257
1998    235
2004    232
2017    232
2005    228
2002    226
2009    224
2003    220
2001    217
1999    216
1992    214
2014    210
2000    209
2008    207
2010    207
2011    199
1991    198
1993    196
2015    145
2016    141
Name: year, dtype: int64

In [25]:
sorted(only_movies_df.columns.tolist())

['Adaptation by',
 'Also known as',
 'Animation by',
 'Arabic',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cantonese',
 'Chinese',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'French',
 'Genre',
 'Hangul',
 'Hebrew',
 'Hepburn',
 'Japanese',
 'Label',
 'Language',
 'Length',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Picture format',
 'Polish',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Simplified',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Traditional',
 'Venue',
 'Voices of',
 'Written by',
 'Yiddish',
 'imdb_link',
 'title',
 'url',
 'year']

In [26]:
only_movies_df['Polish'].value_counts()

Zimna wojna    1
Name: Polish, dtype: int64

# functions in functions - scope
## consolidate columns
> .pop( )  
>returns the value from the key: value pair

In [27]:
def clean_movie(movie):
    
    movie = dict(movie)
    alt_titles = {}
    
    # combine alternate titles into one list
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles
    
    # combining similar columns names
    def change_col_name(old_name, new_name):
        
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
        
    change_col_name('Directed by', 'Director')
    change_col_name('Country of origin', 'Country')
    change_col_name('Distributed by', 'Distributor')
    change_col_name('Edited by', 'Editor(s)')
    change_col_name('Produced by', 'Producer(s)')
    change_col_name('Producer', 'Producer(s)')
    change_col_name('Productioncompanies ', 'Production company(s)')
    change_col_name('Productioncompany ', 'Production company(s)')
    change_col_name('Original release', 'Release date')
    change_col_name('Released', 'Release date')
    change_col_name('Theme music composer', 'Composer(s)')
    
    return movie

clean_movies = [clean_movie(movie) for movie in wiki_movies]

In [28]:
wiki_movies_df = pd.DataFrame(clean_movies)

sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Created by',
 'Director',
 'Distributor',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Picture format',
 'Preceded by',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Recorded',
 'Release date',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

# regex
### [RegExr](https://regexr.com/)
> str.extract( )  
>takes in a regular expression pattern

In [29]:
wiki_movies_df['imdb_link'].head()

# regex would be "(tt\d{7})"

# ( ) -specify to look for 1 group of text
# \d -match a numerical digit
# { } -match the previous n times

0    https://www.imdb.com/title/tt0098987/
1    https://www.imdb.com/title/tt0098994/
2    https://www.imdb.com/title/tt0099005/
3    https://www.imdb.com/title/tt0099012/
4    https://www.imdb.com/title/tt0099018/
Name: imdb_link, dtype: object

In [31]:
# r -regular expressions use backslashes, which Python also uses for special characters 'r' tell Python that to treat as raw string of text
wiki_movies_df['IMDB_id'] = wiki_movies_df['imdb_link'].str.extract(r"(tt\d{7})")

print(len(wiki_movies_df))

7076

In [32]:
wiki_movies_df['IMDB_id'].head()

0    tt0098987
1    tt0098994
2    tt0099005
3    tt0099012
4    tt0099018
Name: IMDB_id, dtype: object

In [34]:
# drop duplicates
wiki_movies_df.drop_duplicates(subset='IMDB_id', inplace=True)

print(len(wiki_movies_df))

7033

In [35]:
wiki_movies_df.head()

,url,year,imdb_link,title,Screenplay by,Story by,Based on,Starring,Narrated by,Music by,...,Suggested by,alt_titles,Recorded,Venue,Length,Label,Animation by,Color process,Screen story by,IMDB_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","Andrew ""Dice"" Clay","[Cliff Eidelman, Yello]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",NaN,Maurice Jarre,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",NaN,Charles Gross,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",NaN,Maurice Jarre,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099018

In [36]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 46 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     7033 non-null   object
 1   year                    7033 non-null   int64
 2   imdb_link               7033 non-null   object
 3   title                   7032 non-null   object
 4   Screenplay by           2307 non-null   object
 5   Story by                996 non-null    object
 6   Based on                2181 non-null   object
 7   Starring                6849 non-null   object
 8   Narrated by             281 non-null    object
 9   Music by                6440 non-null   object
 10  Cinematography          6342 non-null   object
 11  Release date            7001 non-null   object
 12  Running time            6892 non-null   object
 13  Country                 6797 non-null   object
 14  Language                6789 non-null   object
 15  Budget                  4738 non-null   object
 16  Box office              5485 non-null   object
 17  Director                7033 non-null   object
 18  Distributor             6676 non-null   object
 19  Editor(s)               6485 non-null   object
 20  Producer(s)             6831 non-null   object
 21  Production company(s)   5355 non-null   object
 22  Written by              4543 non-null   object
 23  Genre                   110 non-null    object
 24  Original language(s)    158 non-null    object
 25  Original network        125 non-null    object
 26  Composer(s)             75 non-null     object
 27  Executive producer(s)   97 non-null     object
 28  Production location(s)  47 non-null     object
 29  Picture format          64 non-null     object
 30  Audio format            61 non-null     object
 31  Voices of               2 non-null      object
 32  Followed by             9 non-null      object
 33  Created by              10 non-null     object
 34  Preceded by             10 non-null     object
 35  Adaptation by           2 non-null      object
 36  Suggested by            1 non-null      object
 37  alt_titles              21 non-null     object
 38  Recorded                2 non-null      object
 39  Venue                   1 non-null      object
 40  Length                  2 non-null      object
 41  Label                   2 non-null      object
 42  Animation by            2 non-null      object
 43  Color process           1 non-null      object
 44  Screen story by         1 non-null      object
 45  IMDB_id                 7033 non-null   object
dtypes: int64(1), object(45)
memory usage: 2.5+ MB

# list comprehension on each column
> .isnull( ) -return boolean  
> .sum() -add up all those booleans  
> if that sum is less than 90% of the length of the entire dataframe

In [37]:
[column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

['url',
 'year',
 'imdb_link',
 'title',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Music by',
 'Cinematography',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Director',
 'Distributor',
 'Editor(s)',
 'Producer(s)',
 'Production company(s)',
 'Written by',
 'IMDB_id']

In [38]:
wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]

In [40]:
wiki_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7033 entries, 0 to 7075
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url                    7033 non-null   object
 1   year                   7033 non-null   int64
 2   imdb_link              7033 non-null   object
 3   title                  7032 non-null   object
 4   Screenplay by          2307 non-null   object
 5   Story by               996 non-null    object
 6   Based on               2181 non-null   object
 7   Starring               6849 non-null   object
 8   Music by               6440 non-null   object
 9   Cinematography         6342 non-null   object
 10  Release date           7001 non-null   object
 11  Running time           6892 non-null   object
 12  Country                6797 non-null   object
 13  Language               6789 non-null   object
 14  Budget                 4738 non-null   object
 15  Box office             5485 non-null   object
 16  Director               7033 non-null   object
 17  Distributor            6676 non-null   object
 18  Editor(s)              6485 non-null   object
 19  Producer(s)            6831 non-null   object
 20  Production company(s)  5355 non-null   object
 21  Written by             4543 non-null   object
 22  IMDB_id                7033 non-null   object
dtypes: int64(1), object(22)
memory usage: 1.3+ MB

In [44]:
wiki_movies_df['Box office'].head()

0       $21.4 million
1        $2.7 million
2         $57,718,089
3          $7,331,647
4    $6,939,946 (USA)
Name: Box office, dtype: object

In [41]:
wiki_movies_df.dtypes

url                      object
year                      int64
imdb_link                object
title                    object
Screenplay by            object
Story by                 object
Based on                 object
Starring                 object
Music by                 object
Cinematography           object
Release date             object
Running time             object
Country                  object
Language                 object
Budget                   object
Box office               object
Director                 object
Distributor              object
Editor(s)                object
Producer(s)              object
Production company(s)    object
Written by               object
IMDB_id                  object
dtype: object

In [46]:
box_office = wiki_movies_df['Box office'].dropna()

box_office

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...
7070       $19.4 million
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
Name: Box office, Length: 5485, dtype: object

# regex only work on strings

> .map( )

In [47]:
def not_string(x):
    return type(x) != str

box_office[box_office.map(not_string)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

# lambda function

> lambda *arguments: expression*  
> automatically returns a variable

In [48]:
box_office[box_office.map(lambda x: type(x) != str)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

# use blank space as separator along with join
> .join( )

In [49]:
box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)

# re module
## built in Python module for regex

In [50]:
#import re

In [53]:
box_office

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...
7070       $19.4 million
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
Name: Box office, Length: 5485, dtype: object

In [77]:
box_office_form1 = r'\$\s*\d+\.?\d*\s*[mb]illi?on'

# count values that match regex form
> .str.contains(flags=re.IGNORECASE, na=False)

In [58]:
# count total returned as true with .sum()
box_office.str.contains(box_office_form1, flags=re.IGNORECASE, na=False).sum()

3896

In [72]:
box_office_form2 = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

box_office.str.contains(box_office_form2, flags=re.IGNORECASE, na=False).sum()

1559

In [78]:
matches_form_one = box_office.str.contains(box_office_form1, flags=re.IGNORECASE, na=False)
matches_form_two = box_office.str.contains(box_office_form2, flags=re.IGNORECASE, na=False)

In [62]:
matches_form_one

0        True
1        True
2       False
3       False
4       False
        ...
7070     True
7071     True
7072     True
7073     True
7074     True
Name: Box office, Length: 5485, dtype: bool

# check which entries do not fit expected format(s)

> ~ negation operator (tilde)  
> & logical AND (ampersand)  
> | logical OR (pipe)

In [79]:
box_office[~matches_form_one & ~matches_form_two]

600                      $5000 (US)
1070                     35,254,617
1480                     £3 million
1865                   ¥1.1 billion
2032                            N/A
2091                           $309
2665    926,423 admissions (France)
3631                            TBA
3879       CN¥3.650 million (China)
4116                     £7,385,434
4306                            $30
4561        $45.2k (only in Turkey)
5447                          £2.56
5784                       413 733$
6013                        Unknown
6369                          $111k
6370                           $588
6593                 less than $372
6843                        8 crore
Name: Box office, dtype: object

In [75]:
box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

# extract
> .str.extract( )  
> returns a DataFrame where every column is the data that matches a capture group

In [81]:
box_office.str.extract(f'({box_office_form1}|{box_office_form2})')

                  0
0     $21.4 million
1      $2.7 million
2       $57,718,089
3        $7,331,647
4        $6,939,946
...             ...
7070  $19.4 million
7071  $41.9 million
7072  $76.1 million
7073  $38.4 million
7074   $5.5 million

[5485 rows x 1 columns]

# function to convert to numeric values
> re.match(*pattern, string*)  
>
> re.sub(*pattern, replacement_string, string*)

In [85]:
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan
    
    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):
        
        # remove dollar sign and " million"
        s = re.sub('\$|\s|[a-zA-Z]','', s)
        
        # convert to float and multiply by a million
        value = float(s) * 10**6
        
        # return value
        return value
    
    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):
        
        # remove dollar sign and " billion"
        s = re.sub('\$|\s|[a-zA-Z]','', s)
        
        # convert to float and multiply by a billion
        value = float(s) * 10**9
        
        # return value
        return value
    
    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):
        
        # remove dollar sign and commas
        s = re.sub('\$|,','', s)
        
        # convert to float
        value = float(s)
        
        # return value
        return value
    
    # otherwise, return NaN
    else:
        return np.nan

In [86]:
wiki_movies_df['box_office'] = box_office.str.extract(f'({box_office_form1}|{box_office_form2})', flags=re.IGNORECASE)[0].apply(parse_dollars)

In [88]:
wiki_movies_df['box_office'].head(10)

0    21400000.0
1     2700000.0
2    57718089.0
3     7331647.0
4     6939946.0
5           NaN
6           NaN
7           NaN
8           NaN
9      855810.0
Name: box_office, dtype: float64

In [89]:
wiki_movies_df.drop('Box office', axis=1, inplace=True)

In [91]:
wiki_movies_df.head()

,url,year,imdb_link,title,Screenplay by,Story by,Based on,Starring,Music by,Cinematography,...,Language,Budget,Director,Distributor,Editor(s),Producer(s),Production company(s),Written by,IMDB_id,box_office
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","[Cliff Eidelman, Yello]",Oliver Wood,...,English,$20 million,Renny Harlin,20th Century Fox,Michael Tronick,"[Steve Perry, Joel Silver]",Silver Pictures,NaN,tt0098987,21400000.0
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Maurice Jarre,Mark Plummer,...,English,$6 million,James Foley,Avenue Pictures,Howard E. Smith,"[Ric Kidney, Robert Redlin]",Avenue Pictures,NaN,tt0098994,2700000.0
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Charles Gross,Roger Deakins,...,"[English, Lao]",$35 million,Roger Spottiswoode,TriStar Pictures,"[John Bloom, Lois Freeman-Fox]",Daniel Melnick,"[Carolco Pictures, IndieProd Company]",NaN,tt0099005,57718089.0
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,Carlo Di Palma,...,English,$12 million,Woody Allen,Orion Pictures,Susan E. Morse,Robert Greenhut,NaN,Woody Allen,tt0099012,7331647.0
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Maurice Jarre,Russell Boyd,...,English,$25 million,John Cornell,Paramount Pictures,David Stiven,John Cornell,NaN,Paul Hogan,tt0099018,6939946.0

# budget

In [ ]:
wiki_movies_df['Budget'].tail(10)

In [94]:
budget = wiki_movies_df['Budget'].dropna()

In [95]:
budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)

In [96]:
budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

In [100]:
matches_form_one = budget.str.contains(box_office_form1, flags=re.IGNORECASE, na=False)
matches_form_two = budget.str.contains(box_office_form2, flags=re.IGNORECASE, na=False)
budget = budget.str.replace(r'\[\d+\]\s*', '')
budget[~matches_form_one & ~matches_form_two]

C:\Anaconda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

136                         Unknown
204     60 million Norwegian Kroner
478                         Unknown
1226                        Unknown
1278                            HBO
1374                     £6,000,000
1397                     13 million
1480                   £2.8 million
1734                   CAD2,000,000
1913     PHP 85 million (estimated)
1948                    102,888,900
1953                   3,500,000 DM
1973                     ₤2,300,874
2281                     $14 milion
2451                     ₤6,350,000
3144                   € 40 million
3418                        $218.32
3802                   £4.2 million
3906                            N/A
3959                    760,000 USD
4470                       19 crore
4641                    £17 million
5424                            N/A
5447                     £4 million
5671                    €14 million
5687                   $ dead link]
6385                  £ 12 million
6593                     £3 million
6821                  £12.9 million
6843                      3.5 crore
6895                        919,000
7070                   €4.3 million
Name: Budget, dtype: object

In [101]:
budget[~matches_form_one & ~matches_form_two].count()

32

In [103]:
wiki_movies_df['budget'] = budget.str.extract(f'({box_office_form1}|{box_office_form2})', flags=re.IGNORECASE)[0].apply(parse_dollars)
wiki_movies_df.drop('Budget', axis=1, inplace=True)

# release date

In [105]:
release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)

In [106]:
release_date.head(10)

0                         July 11, 1990 ( 1990-07-11 )
1    May 17, 1990 ( 1990-05-17 ) (Cannes Film Marke...
2                       August 10, 1990 ( 1990-08-10 )
3                     December 25, 1990 ( 1990-12-25 )
4                                    December 19, 1990
5                        March 22, 1990 ( 1990-03-22 )
6    October 6, 1990 ( 1990-10-06 ) ( New York Film...
7                         March 8, 1991 ( 1991-03-08 )
8                         March 7, 1990 ( 1990-03-07 )
9                            February 23, 1990 ( USA )
Name: Release date, dtype: object

In [107]:
release_date.tail(10)

7066    November 26, 2018 ( 2018-11-26 ) ( Empire, Lei...
7067    December 3, 2018 ( 2018-12-03 ) ( Sony Center ...
7068     December 21, 2018 ( 2018-12-21 ) (United States)
7069     December 21, 2018 ( 2018-12-21 ) (United States)
7070    10 May 2018 ( 2018-05-10 ) ( Cannes ) 8 June 2...
7071     December 25, 2018 ( 2018-12-25 ) (United States)
7072    December 11, 2018 ( 2018-12-11 ) ( Samuel Gold...
7073    November 8, 2018 ( 2018-11-08 ) ( AFI Fest ) D...
7074    August 31, 2018 ( 2018-08-31 ) ( Telluride ) D...
7075                      28 December 2018 ( 2018-12-28 )
Name: Release date, dtype: object

In [109]:
#date_form_1 = r'\D\s\d{1,2}\,\d{4}'
#date_form_2 =
#date_form_3 = r'\D\d{4)'
#date_form_4 = r'\d{4)'

In [110]:
date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]?\d,\s\d{4}'
date_form_two = r'\d{4}.[01]\d.[0123]\d'
date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
date_form_four = r'\d{4}'

In [ ]:
release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)

# to_datetime( )
infer_datetime_format=True

In [111]:
wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)

In [113]:
wiki_movies_df['release_date'].tail()

7071   2018-12-25
7072   2018-12-11
7073   2018-11-08
7074   2018-08-31
7075   2018-12-01
Name: release_date, dtype: datetime64[ns]

# running time

In [114]:
running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)

In [115]:
running_time

0                                 102 minutes
1                                 114 minutes
2                                 113 minutes
3                                 106 minutes
4                                  95 minutes
                        ...
7071                               90 minutes
7072                              132 minutes
7073                              120 minutes
7074                              123 minutes
7075    Variable; 90 minutes for default path
Name: Running time, Length: 6892, dtype: object

In [116]:
running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False).sum()

6528

In [117]:
running_time[running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False) != True]

9                                                 102 min
26                                                 93 min
28                                                32 min.
34                                                101 min
35                                                 97 min
                              ...
6500       114 minutes [1] 120 minutes (extended edition)
6643                                             104 mins
6709    90 minutes (theatrical) [1] 91 minutes (unrate...
7057    108 minutes (Original cut) 98 minutes (UK cut)...
7075                Variable; 90 minutes for default path
Name: Running time, Length: 364, dtype: object

In [119]:
running_time[running_time.str.contains(r'\d*\s*m', flags=re.IGNORECASE, na=False) != True]

1551     varies
3925    4 hours
Name: Running time, dtype: object

In [121]:
running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')

> .to_numeric( )  
> .fillna( )

In [122]:
running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)

apply a function that will convert the hour capture groups and minute capture groups to minutes if the pure minutes capture group is zero

In [123]:
wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)

In [124]:
wiki_movies_df.drop('Running time', axis=1, inplace=True)

In [125]:
wiki_movies_df.head(10)

,url,year,imdb_link,title,Screenplay by,Story by,Based on,Starring,Music by,Cinematography,...,Distributor,Editor(s),Producer(s),Production company(s),Written by,IMDB_id,box_office,budget,release_date,running_time
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","[Cliff Eidelman, Yello]",Oliver Wood,...,20th Century Fox,Michael Tronick,"[Steve Perry, Joel Silver]",Silver Pictures,NaN,tt0098987,21400000.0,20000000.0,1990-07-11,102.0
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Maurice Jarre,Mark Plummer,...,Avenue Pictures,Howard E. Smith,"[Ric Kidney, Robert Redlin]",Avenue Pictures,NaN,tt0098994,2700000.0,6000000.0,1990-05-17,114.0
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Charles Gross,Roger Deakins,...,TriStar Pictures,"[John Bloom, Lois Freeman-Fox]",Daniel Melnick,"[Carolco Pictures, IndieProd Company]",NaN,tt0099005,57718089.0,35000000.0,1990-08-10,113.0
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,Carlo Di Palma,...,Orion Pictures,Susan E. Morse,Robert Greenhut,NaN,Woody Allen,tt0099012,7331647.0,12000000.0,1990-12-25,106.0
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Maurice Jarre,Russell Boyd,...,Paramount Pictures,David Stiven,John Cornell,NaN,Paul Hogan,tt0099018,6939946.0,25000000.0,1990-12-19,95.0
5,https://en.wikipedia.org/wiki/The_Ambulance,1990,https://www.imdb.com/title/tt0099026/,The Ambulance,NaN,NaN,NaN,"[Eric Roberts, James Earl Jones, Red Buttons, ...",Jay Chattaway,Jacques Haitkin,...,Triumph Releasing Corporation,"[Claudia Finkle, Armond Leibowitz]","[Larry Cohen, Moctesuma Esparza, Robert Katz]",Epic Productions,Larry Cohen,tt0099026,NaN,NaN,1990-03-22,95.0
6,https://en.wikipedia.org/wiki/American_Dream_(...,1990,https://www.imdb.com/title/tt0099028/,American Dream,NaN,NaN,NaN,NaN,Michael Small,"[Tom Hurwitz, Mathieu Roberts, Nesya Shapiro]",...,Prestige Films,"[Cathy Caplan, Thomas Haneke, Lawrence Silk]","[Arthur Cohn, Barbara Kopple]","[Cabin Creek, Catholic Communication Campaign,...",NaN,tt0099028,NaN,NaN,1990-10-06,100.0
7,https://en.wikipedia.org/wiki/American_Ninja_4...,1990,https://www.imdb.com/title/tt0101326/,American Ninja 4: The Annihilation,NaN,NaN,NaN,"[Michael Dudikoff, David Bradley, James Booth,...",NaN,NaN,...,Cannon Group,NaN,Ovidio G Assonitis,NaN,David Geeves,tt0101326,NaN,NaN,1991-03-08,99.0
8,https://en.wikipedia.org/wiki/Andre%27s_Mother,1990,https://www.imdb.com/title/tt0099037/,Andre's Mother,NaN,NaN,NaN,"[Richard Thomas, Sada Thompson, Sylvia Sidney]",Jonathan Sheffer,Bobby Bukowski,...,Public Broadcasting Service,Jeffrey Wolf,"[Sarah Green, Deborah Reinisch]",NaN,Terrence McNally,tt0099037,NaN,NaN,1990-03-07,50.0
9,https://en.wikipedia.org/wiki/Angel_Town_(film),1990,https://www.imdb.com/title/tt0099039/,Angel Town,NaN,NaN,NaN,"[Olivier Gruner, Theresa Saldana, Frank Aragon...",Terry Plumeri,John LeBlanc,...,Imperial Entertainment,Duane Hartzell,"[Ash R. Shah, Eric Karson]",NaN,S. Warren,tt0099039,855810.0,NaN,1990-02-23,102.0